on:
  push:
    branches: [ "main" ] # La pipeline parte quando carichi su main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Usa un server Linux di GitHub

    steps:
      # 1. Scarica il tuo codice sulla macchina di GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installa Java (fondamentale per Gradle)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Test del segnale
        run: echo ">>> La pipeline Ã¨ arrivata qui dopo aver installato java"

      - name: Run Tests with Gradle
        run: |
         echo ">>> Inizio esecuzione dei test..."
                   ./gradlew test
                   echo ">>> Test finiti con successo!"


      # --- QUI VA IL TEST ---
      - name: Run Tests with Gradle
        run: ./gradlew test  # Questo comando cerca ed esegue tutti i test in src/test

      # 3. Compila il JAR (come fai nel Dockerfile, ma qui per testarlo)
      - name: Build with Gradle
        run: ./gradlew build

      # 4. Login su Docker Hub (servono le tue credenziali salvate su GitHub)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Build dell'immagine Docker e Push
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: lorenzosarti22/hackhub-backend:latest